# Generated by Django 3.1.3 on 2020-11-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedfile',
            name='file_original',
            field=models.FileField(blank=True, null=True, upload_to='data_original/', verbose_name='파일'),
        ),
        migrations.AddField(
            model_name='parsedfile',
            name='file_parsed',
            field=models.FileField(blank=True, null=True, upload_to='data_parsed/', verbose_name='처리된 파일'),
        ),
        migrations.AlterField(
            model_name='parsedfile',
            name='end_date',
            field=models.DateField(verbose_name='수집 종료 날짜'),
        ),
        migrations.AlterField(
            model_name='parsedfile',
            name='start_date',
            field=models.DateField(verbose_name='수집 시작 날짜'),
        ),
    ]
