# Generated by Django 3.1.3 on 2020-11-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicdb', '0002_auto_20201119_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsedfile',
            name='directory',
        ),
    ]
