# Generated by Django 3.1.3 on 2020-11-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicdb', '0003_remove_parsedfile_directory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappinginfo',
            old_name='orginal_column_name',
            new_name='original_column_name',
        ),
        migrations.RenameField(
            model_name='mappinginfo',
            old_name='orginal_schema_name',
            new_name='original_schema_name',
        ),
    ]
