# Generated by Django 3.1.3 on 2020-11-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsefile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUpload',
            new_name='File',
        ),
    ]
