# Generated by Django 3.1.3 on 2020-11-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsefile', '0003_auto_20201118_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='originFile',
        ),
    ]
