# Generated by Django 3.1.3 on 2020-11-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsefile', '0004_auto_20201119_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='originfile',
            old_name='data',
            new_name='file_original',
        ),
    ]
