# Generated by Django 3.1.3 on 2020-11-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsefile', '0005_auto_20201119_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originfile',
            name='name',
        ),
    ]
